### ISSUE TITLE
Issue @ mangafox

### ISSUE THREAD

**Issue by freckhard** [briefbanane/manga-downloader#4]
Hallo Fabian/Briefbanane, habe ein Bug bei mangafox, sowohl mit der sh von April, als auch mit der aktuellen Version. Lieben Gruß, Eckhard/freckhard

Hello Fabian/Briefbanane, I have found a bug regarding mangafox, with the sh version from april as well as the current one. Regards, Eckhard/freckhard.

%
%
%

$ ./manga-downloader.sh http://mangafox.me/manga/nanatsu_no_taizai/vTBD/c125/1.html
Retrieving URL list...
done
Catching up to desired chapter...
Downloading chapter 125 of volume TBD
curl: option -: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
This shouldn't happen. Please try again and if it still fails, report a bug at github.com/briefbanane/manga-downloader
and include the last URL: http://mangafox.me/manga/nanatsu_no_taizai/vTBD/c125/1.html image-URL:  and curl-return: 2

**Comment by briefbanane** [comment]
Thanks for the report.

The problem was the server sending compressed content. Until now there was never a case where that happened and I haven't thought about that possibility before. The fix 973a6ce811614c1694037a774c9b611931cb04b3 was simple (debbuging took a bit longer) and it should work now.

Regards, Fabian
