### ISSUE TITLE
Mangahere.co support?

### ISSUE THREAD

**Issue by Hackswell** [briefbanane/manga-downloader#5]
Here's the example I was trying to download... it looks like it should be supported according to the regexes, but I'm missing something on how to link it in. :(

http://www.mangahere.co/manga/return_to_labyrinth/v01/c000/

**Comment by briefbanane** [comment]
I added initial support for the site with commit 4cbebbf .

You are right that the regular expressions are already there, but unfortunately it has also very much to do with how the server handles requests and the specific html structure, which is quite different from mangafox.me. Because of that I'd like to make a different function for each site, even if the differences are minor. When a site changes, it will only be necessary to fix the specific function and it won't break the other working ones.

**Comment by Hackswell** [comment]
Thank you very much!
