### ISSUE TITLE
Won't resume downloads

### ISSUE THREAD

**Issue by raincrash** [briefbanane/manga-downloader#6]
URL used: http://www.mangapanda.com/inuyasha
System: OS X 10.11.3 (El Cap)

**Comment by briefbanane** [comment]
I cannot reproduce here. Could you please be a bit more specific: where does the download hang? Which chapter and page? What's the console output at the end?

Have you tried restarting the program with the chapter you're currently at (you can put example given  http://www.mangapanda.com/inuyasha/6 if you're at chapter 6)? Otherwise try to delete the last downloaded image and restart the program with that chapter.

**Comment by raincrash** [comment]
After downloading a couple of chapters, I ran the script again.
last URL: http://www.mangapanda.com/inuyasha/1/1 image-URL: http://i7.mangapanda.com/inuyasha/1/inuyasha-366015.jpg and curl-return: 33

**Comment by briefbanane** [comment]
Try adding the following code after line 50 (between curlreturn=$? and done) in the function download:

            
if [ $curlreturn -eq 33 ]
then
rm $2
curl -s -A "Mozilla/5.0 (X11; Linux x86_64; rv:23.0)" --compressed --max-redirs 0 $1 -o $2;curlreturn=$?
fi

and test again with http://www.mangapanda.com/inuyasha. Please tell me if that works,

 And you don't need to restart at the beginning, you can add the chapter and page numbers to the URL and the script will start downloading there. If you already have downloaded the chapters 1-7 and two pages of chapter 8 for example you can call:

> mangadownloader.sh http://www.mangapanda.com/inuyasha/8/3

and the script will start downloading from chapter 8 page 3 onwards.
